void display_init(void);
void display_backlight_process(void);
void display_splash(void);
void display_update(void) ;
void display_clear(void);
void display_upgrade_start(void);
void display_upgrade_progress(unsigned int percent);
void display_upgrade_complete(void);
void display_upgrade_error(void);
void display_cycle_next_mode(void);
void display_qr_mode_enable(bool enabled);
bool display_qr_mode_is_enabled(void);
void display_QRcode(const char* Message);
